### ISSUE TITLE
How are changes to the java-cnb build and detect communicated?

### ISSUE THREAD

**Issue by shamus** [cloudfoundry/java-cnb#3]
Recently the `cflinuxfs3` builder image was updated. This update resulted in the removal of the `archiveexpanding` buildpack:

➜ pack inspect-builder cloudfoundry/cnb:0.0.68-cflinuxfs3

```
Detection Order:
  Group #1:
    org.cloudfoundry.archiveexpanding             (optional)
    org.cloudfoundry.openjdk
    org.cloudfoundry.buildsystem                  (optional)
    org.cloudfoundry.jvmapplication
    org.cloudfoundry.tomcat                       (optional)
    org.cloudfoundry.springboot                   (optional)
    org.cloudfoundry.distzip                      (optional)
    org.cloudfoundry.procfile                     (optional)
    org.cloudfoundry.azureapplicationinsights     (optional)
    org.cloudfoundry.debug                        (optional)
    org.cloudfoundry.googlestackdriver            (optional)
    org.cloudfoundry.jdbc                         (optional)
    org.cloudfoundry.jmx                          (optional)
    org.cloudfoundry.springautoreconfiguration    (optional)
```

➜ pack inspect-builder cloudfoundry/cnb:cflinuxfs3

```
Detection Order:
  Group #1:
    org.cloudfoundry.openjdk
    org.cloudfoundry.buildsystem                  (optional)
    org.cloudfoundry.jvmapplication
    org.cloudfoundry.tomcat                       (optional)
    org.cloudfoundry.springboot                   (optional)
    org.cloudfoundry.distzip                      (optional)
    org.cloudfoundry.procfile                     (optional)
    org.cloudfoundry.azureapplicationinsights     (optional)
    org.cloudfoundry.debug                        (optional)
    org.cloudfoundry.googlestackdriver            (optional)
    org.cloudfoundry.jdbc                         (optional)
    org.cloudfoundry.jmx                          (optional)
    org.cloudfoundry.springautoreconfiguration    (optional)
```

A consequence of removing `archiveexpanding` is that it changes the semantics of `pack build`. With archiveexpanding in the detection group, it is possible to run `pack build some-project` from within the directory that contains the jar/war and successfully generate an image which will run some-project.

Now that it's removed, that command will fail with the following (truncated) output:

```
[detector] ERROR: No buildpack groups passed detection.
[detector] ERROR: Please check that you are running against the correct path.
[detector] ERROR: failed to detect: no buildpacks participating
ERROR: failed with status code: 6
```

The resolution is to change the pack invocation to `pack build -p path-to-warfile some-project`.

I have no strong opinion about the value provided by the archiveexpanding buildpack. However the behavior of the `pack build` command changing with an update to the cflinuxfs3 builder (and mitigation steps) was a surprise and a proved to be a bit of a challenge to track down.

I have two questions:
- Was it intentional to make specifying `--path` required?
- How are builder changes (and their mitigation steps) which can impact build / detect behavior communicated?

**Comment by shamus** [comment]
cc @cloudfoundry/cf-uaa

**Comment by nebhale** [comment]
> Was it intentional to make specifying --path required?

Yes.  In fact we'd always assumed that's what people were doing, and hadn't even thought that people might be pushing a directory with only a built JAR inside of it.  The goal is to make this equivalent to the `cf push` behavior around archives and it now is.

> How are builder changes (and their mitigation steps) which can impact build / detect behavior communicated?

This would typically go out as semver changes to the major along with a release note.  At this time, we're very much pre-production and so we're not holding to that strictly.  That being said, _some_ of the builders in the world did [rev major versions](https://github.com/cloudfoundry/java-cnb/commit/01d4afff18e978bf6e64f2cc0b8b52992a4dd453) (note the oldest tag) for it, but not all.

This could certainly have been communicated better, but I had expected it to be non-breaking (not envisioning how you were using it).

**Comment by shamus** [comment]
>  and hadn't even thought that people might be pushing a directory with only a built JAR inside of i

Isn't that the use case described here:

https://buildpacks.io/docs/app-journey/

**Comment by shamus** [comment]
>  and hadn't even thought that people might be pushing a directory with only a built JAR inside of it

I can't recall exactly how we came to that usage, but it was by example. I can imagine that [these](https://buildpacks.io/docs/app-journey/) directions were followed and it was a happy accident that the war was unpacked.

At any rate, I totally get that this repo is pre-production. I want to be able to understand what is changing while it stabilizes so that we can address issues in our environment (like this) as they come up.
